baseURL = "https://javayou.com"
languageCode = "en-us"
title = "JavaYou"
theme = "ananke"
publishDir = "public"
disableKinds = []

# Pagination settings
paginate = 20

[params]
  description = "Learn Java, Spring Boot, and web development step by step"
  showMenu = true
  showBurger = true
  showPostSummary = true
  showReadingTime = true
  # Show more posts on the homepage
  homePostsLimit = 20

[outputs]
  home = ["HTML", "RSS", "JSON"] # Update trigger