baseURL = "https://javayou.com"
languageCode = "en-us"
title = "JavaYou"
theme = "ananke"
publishDir = "public"
disableKinds = []

[params]
  description = "Learn Java, Spring Boot, and web development step by step"
  showMenu = true
  showBurger = true
  showPostSummary = true
  showReadingTime = true

[outputs]
  home = ["HTML", "RSS", "JSON"]# Update trigger



# Force rebuild - 2025-08-19

publishDir = "public"

# Force rebuild after removing hugo.exe